ALTER TABLE games AUTO_INCREMENT = 1;
SELECT AUTO_INCREMENT FROM information_schema.TABLES 
WHERE TABLE_NAME = 'games' AND TABLE_SCHEMA = 'inventory';

CREATE TABLE IF NOT EXISTS USERS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(100) UNIQUE,
	password VARCHAR(250),
	first_name VARCHAR(100),
	last_name VARCHAR(100),
	email VARCHAR(100),
	phone_number VARCHAR(16),
	last_updated DATETIME,
	created_ts DATETIME
);

CREATE TABLE IF NOT EXISTS ROLES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	role_name VARCHAR(50),
	role_description TEXT
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT,
	role_id INT,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (role_id) REFERENCES ROLES(id)
);