CREATE TABLE IF NOT EXISTS games (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(150) NOT NULL UNIQUE,
	price DECIMAL(10, 2) NOT NULL,
	category VARCHAR(100) NOT NULL,
	description TEXT
);

CREATE TABLE IF NOT EXISTS USERS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(100) UNIQUE,
	password VARCHAR(250),
	first_name VARCHAR(100),
	last_name VARCHAR(100),
	email VARCHAR(100),
	phone_number VARCHAR(16),
	last_updated DATETIME,
	created_ts DATETIME,
	role VARCHAR(50) NOT NULL DEFAULT 'CUSTOMER'
);

CREATE TABLE IF NOT EXISTS ROLES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	role_name VARCHAR(50) UNIQUE,
	role_description TEXT
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNIQUE,
	role_id INT,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (role_id) REFERENCES ROLES(id)
);