CREATE DATABASE IF NOT EXISTS INVENTORY;
USE INVENTORY;

CREATE TABLE IF NOT EXISTS GAMES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PRICE DECIMAL (10, 2) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	DESCRIPTION TEXT
);

CREATE TABLE IF NOT EXISTS USERS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(100) UNIQUE,
	password VARCHAR(250),
	first_name VARCHAR(100),
	last_name VARCHAR(100),
	email VARCHAR(100),
	phone_number VARCHAR(16),
	last_updated DATETIME,
	created_ts DATETIME
);

CREATE TABLE IF NOT EXISTS ROLES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	role_name VARCHAR(50),
	role_description TEXT
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT,
	role_id INT,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (role_id) REFERENCES ROLES(id)
);