CREATE DATABASE IF NOT EXISTS INVENTORY;
USE INVENTORY;

CREATE TABLE IF NOT EXISTS GAMES (
	id INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PRICE DECIMAL (10, 2) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	DESCRIPTION TEXT
	
);